name: Publish emporus-googletransx Python Package

on:
  push:
    branches:
      - poetrification
      
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  Publish_Package:
    name: Publish emporus-googletransx Package to AWS CodeArtifact
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Connect to private pip ripo
        run: |
          export CODEARTIFACT_REPOSITORY_URL=`aws codeartifact get-repository-endpoint --domain emporus --domain-owner 568780636633 --repository emporus-pypi --format pypi --query repositoryEndpoint --output text`
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain emporus --domain-owner 568780636633 --query authorizationToken --output text`
          export CODEARTIFACT_USER=aws
          # configuring the repo in poetry
          poetry config repositories.emporus-pypi $CODEARTIFACT_REPOSITORY_URL
          poetry config http-basic.emporus-pypi $CODEARTIFACT_USER $CODEARTIFACT_AUTH_TOKEN
          
      - name: Build and publish   
        run: |
          poetry install
          poetry build
          poetry publish --repository emporus-pypi
